name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Run tests
        run: npm test
      
      - name: Upload coverage
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v4
        with:
          directory: ./coverage
          flags: unittests
          
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Check formatting
        run: npm run format:check
      
      - name: Lint
        run: npm run lint
          
  cli-smoke-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build
      
      - name: Test loomtype init
        run: |
          # Create a test directory
          mkdir -p test-project
          cd test-project
          
          # Run loomtype init using the built binary
          node ../bin/cli.js init
          
          # Verify .loomtype.yaml was created
          test -f .loomtype.yaml
      
      - name: Test loomtype verify
        run: |
          cd test-project
          
          # Create a simple .loomtype.yaml for testing
          cat > .loomtype.yaml << 'EOF'
          version: 1.0
          name: Test Project
          description: Testing loomtype verify
          
          patterns:
            'Test Pattern':
              - This is a test pattern
          
          verify:
            echo-test:
              check: echo "test output"
              expect: "test output"
              on_fail: "Echo test failed"
          EOF
          
          # Run loomtype verify
          node ../bin/cli.js verify